name: common_koreas_app
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  bloc: ^8.1.1
  equatable: ^2.0.5
  freezed_annotation: ^2.2.0
  http: ^0.13.5
  json_annotation: ^4.8.0
  stream_transform: ^2.1.0

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  lints: ^2.0.0
  test: ^1.21.0
